---
# tasks file for .

- name: Rename the requirements file
  delegate_to: localhost
  # copy: 
  #   src: '{{playbook_dir}}//new_directory/requirements.yml'
  #   dest: '{{playbook_dir}}//new_directory/requirements.txt'
    # mode: '0500'
  command: mv '{{playbook_dir}}//new_directory/requirements.yml' '{{playbook_dir}}//new_directory/requirements.txt' 
  args:
    creates: '{{playbook_dir}}//new_directory/requirements.txt'
    removes: '{{playbook_dir}}//new_directory/requirements.yml'

- name: Rename the requirements file
  delegate_to: localhost
  command: cat '{{playbook_dir}}//new_directory/requirements.txt'
      register: out

    - name: Display Output
      debug: var=out
